# Generated by Django 4.1.6 on 2023-03-01 13:36
# Modified by hand to add Group records to the database for our User Roles

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')  # django.contrib.auth.models.Group
    Group.objects.bulk_create(
        (
            Group(name='Cinema Manager'),
            Group(name='Account Manager'),
            Group(name='Club Representative'),
            Group(name='Customer')
        )
    )

def delete_groups(apps, schema_editor):
    """
    Reverse migration in case anyone ever needs to undo this one for some reason
    """
    Group = apps.get_model('auth', 'Group')  # django.contrib.auth.models.Group
    Group.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups),
    ]
