# Generated by Django 4.1.2 on 2023-03-12 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UWEFlixApp", "0002_remove_booking_num_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="Showing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UWEFlixApp.movie",
                    ),
                ),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UWEFlixApp.screen",
                    ),
                ),
            ],
        ),
    ]
