# Generated by Django 4.1.6 on 2023-03-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0003_booking_club_booking_date_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
