# Generated by Django 4.1.6 on 2023-03-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0003_booking_club_booking_date_booking_total_price'),
       
    ]

    operations = [
    ]
