# Generated by Django 4.1.6 on 2023-03-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0004_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='images/no_image_available.png', null=True, upload_to='images/'),
        ),
    ]
