# Generated by Django 4.1.7 on 2023-03-21 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UWEFlixApp", "0006_club_balance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="number_of_tickets",
            new_name="number_of_adult_tickets",
        ),
        migrations.AddField(
            model_name="booking",
            name="number_of_child_tickets",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="number_of_student_tickets",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateTimeField(auto_now=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="screening",
            name="seats_remaining",
            field=models.IntegerField(default=0),
        ),
    ]
