# Generated by Django 4.1.6 on 2023-03-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0006_club_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='seats_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
