# Generated by Django 4.1.6 on 2023-03-24 13:12

from django.db import migrations, models
import django.db.models.deletion


def drop_customers(apps, schema_editor):
    """
    User Role CUSTOMER is being dropped, instead "customers" are just anonymous
    Users and a new Role, STUDENT is introduced.
    We're just going to handle this by deleting all Users of Role type CUSTOMER

    Also while we're about it, drop the Customers Group and add a new Students
    Group.
    """
    User = apps.get_model('UWEFlixApp', 'User')
    Group = apps.get_model('auth', 'Group')
    User.objects.filter(role='C').delete()  # NOTE: can't use User.Role.CUSTOMER as apps.get_model() doesn't provide it :(
    Group.objects.get(name='Customer').delete()
    Group.objects.create(name='Student')

class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0006_club_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UWEFlixApp.club'),
        ),
        migrations.RunPython(drop_customers, lambda a, s: None),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('M', 'Cinema Manager'), ('A', 'Account Manager'), ('R', 'Club Representative'), ('S', 'Student')], default='S', max_length=1),
        ),
    ]
