# Generated by Django 4.1.6 on 2023-04-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0009_alter_user_options_user_club_alter_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='members_have_club',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('role', 'R'), _negated=True), ('club__isnull', True), _connector='OR'), name='club_reps_have_club', violation_error_message='Club Rep must have a Club!'),
        ),
    ]
