# Generated by Django 4.1.6 on 2023-04-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0009_alter_screening_options_alter_movie_minutes_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='minutes_long',
            new_name='running_time',
        ),
    ]
