# Generated by Django 4.1.6 on 2023-04-18 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0010_remove_user_members_have_club_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='club_reps_have_club',
        ),
        migrations.AddField(
            model_name='user',
            name='requested_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_club', to='UWEFlixApp.club'),
        ),
    ]
