# Generated by Django 4.1.6 on 2023-04-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0011_user_requested_club'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='club_reps_have_club',
        ),
    ]
