# Generated by Django 4.1.6 on 2023-04-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0011_remove_user_club_reps_have_club_user_requested_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='card_number',
            field=models.CharField(max_length=128),
        ),
    ]
