# Generated by Django 4.1.6 on 2023-04-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0011_remove_user_club_reps_have_club_user_requested_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
    ]
