# Generated by Django 4.1.6 on 2023-04-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0012_alter_club_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
