# Generated by Django 4.1.7 on 2023-04-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UWEFlixApp", "0012_booking_cancel_requested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="cancel_requested",
            field=models.TextField(default="Active"),
        ),
    ]
