# Generated by Django 4.1.6 on 2023-04-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0012_alter_club_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('R', 'Cancellation Requested'), ('C', 'Cancelled')], default='A', max_length=1),
        ),
    ]
