# Generated by Django 4.1.6 on 2023-04-13 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0013_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screening',
            options={'ordering': ('showing_at',)},
        ),
        migrations.AlterField(
            model_name='movie',
            name='minutes_long',
            field=models.DurationField(validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
