# Generated by Django 4.1.6 on 2023-04-22 17:03

from django.db import migrations, models
import django.db.models.aggregates
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0013_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='seats_remaining',
        ),
        migrations.AddConstraint(
            model_name='screening',
            constraint=models.CheckConstraint(check=models.Q(('screen__capacity__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.aggregates.Sum('booking__number_of_adult_tickets'), '+', django.db.models.aggregates.Sum('booking__number_of_child_tickets')), '+', django.db.models.aggregates.Sum('booking__number_of_student_tickets')))), name='screenings_are_not_overbooked', violation_error_message='Not enough capacity in Screening!'),
        ),
    ]
