# Generated by Django 4.1.6 on 2023-04-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0013_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='seats_remaining',
        ),
    ]
