# Generated by Django 4.1.7 on 2023-04-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UWEFlixApp", "0013_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Active"),
                    ("R", "Cancellation Requested"),
                    ("C", "Cancelled"),
                ],
                default="A",
                max_length=1,
            ),
        ),
    ]
