# Generated by Django 4.1.7 on 2023-04-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UWEFlixApp", "0015_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Cancellation Requested", "Cancellation Requested"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Active",
                max_length=25,
            ),
        ),
    ]
