# Generated by Django 4.1.6 on 2023-04-23 13:49
# Handwritten with love by Josh a short time after <3

import datetime
from math import ceil

import django.core.validators
from django.db import migrations, models


def convert_minutes_long_to_running_time(apps, schema_editor):
    Movie = apps.get_model('UWEFlixApp', 'Movie')
    for movie in Movie.objects.all():
        movie.running_time = datetime.timedelta(minutes=movie.minutes_long)
        movie.save()

def convert_running_time_to_minutes_long(apps, schema_editor):
    Movie = apps.get_model('UWEFlixApp', 'Movie')
    for movie in Movie.objects.all():
        movie.minutes_long = ceil(movie.running_time.total_seconds() / 60)
        movie.save()

class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0017_remove_screening_seats_remaining_and_more'),
    ]

    operations = [
        # add new field with default value
        migrations.AddField(
            model_name='movie',
            name='running_time',
            field=models.DurationField(default=datetime.timedelta(seconds=60), validators=[django.core.validators.MinValueValidator(limit_value=datetime.timedelta(seconds=60))]),
        ),
        # copy and transform values of old rows to new field
        migrations.RunPython(
            convert_minutes_long_to_running_time,
            convert_running_time_to_minutes_long
        ),
        # set old field nullable so it can be un-removed by reverting migration if need be
        migrations.AlterField(
            model_name='movie',
            name='minutes_long',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=1)])
        ),
        # remove old field
        migrations.RemoveField(
            model_name='movie',
            name='minutes_long',
        ),
        # remove default value for new field
        migrations.AlterField(
            model_name='movie',
            name='running_time',
            field=models.DurationField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.timedelta(seconds=60))]),
        ),
    ]
