# Generated by Django 4.1.6 on 2023-04-22 23:09
# Handwritten with love by Josh a short time after <3

import datetime

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UWEFlixApp', '0017_remove_screening_seats_remaining_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='minutes_long',
            new_name='running_time',
        ),
        migrations.AlterField(
            model_name='movie',
            name='running_time',
            field=models.DurationField(validators=[MinValueValidator(limit_value=datetime.timedelta(seconds=60))]),
        ),
    ]
